name: Code Image

on:
  workflow_dispatch:

jobs:
  generate_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - id: generate_image
        uses: JonathanTreffler/Carbon-Action@master
        with:
          code: 'console.log("Test");'
          
      - uses: actions/upload-artifact@v2
        with:
          name: Code
          path: code.png
